permalink: /:year:month:day/:title
url: nicohman.github.io
baseurl: 
# variables
name: "`Yard of Code"
description: it's pronounced grave 


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
